TaskType = "Calibrate"

[CalibrationParameters]
WriteIntermediateFiles = false
MinMS1IsotopicPeaksNeededForConfirmedIdentification = 3
MinMS2IsotopicPeaksNeededForConfirmedIdentification = 2
NumFragmentsNeededForEveryIdentification = 10

[CommonParameters]
TaskDescriptor = "CalibrateTask"
MaxThreadsToUsePerFile = 3
ListOfModsFixed = "Common Fixed\tCarbamidomethyl on C\t\tCommon Fixed\tCarbamidomethyl on U"
ListOfModsVariable = "Common Variable\tOxidation on M"
DoPrecursorDeconvolution = true
UseProvidedPrecursorInfo = true
DeconvolutionIntensityRatio = 3.0
DeconvolutionMaxAssumedChargeState = 12
DeconvolutionMassTolerance = "±4.0000 PPM"
TotalPartitions = 1
ProductMassTolerance = "±25.0000 PPM"
PrecursorMassTolerance = "±15.0000 PPM"
AddCompIons = false
ScoreCutoff = 5.0
ReportAllAmbiguity = true
TopNpeaks = 200
MinRatio = 0.01
TrimMs1Peaks = false
TrimMsMsPeaks = true
UseDeltaScore = false
CalculateEValue = false
QValueOutputFilter = 1.0
DissociationType = "HCD"
CustomIons = []
AssumeOrphanPeaksAreZ1Fragments = true
MaxHeterozygousVariants = 4
MinVariantDepth = 1

[CommonParameters.DigestionParams]
MaxMissedCleavages = 2
InitiatorMethionineBehavior = "Variable"
MinPeptideLength = 7
MaxPeptideLength = 2147483647
MaxModificationIsoforms = 1024
MaxModsForPeptide = 2
Protease = "trypsin"
SearchModeType = "Full"
FragmentationTerminus = "Both"
SpecificProtease = "trypsin"
